[manifest]
id = "dk64_tag_anywhere"
version = "1.0.3"
display_name = "Tag Anywhere"
description =  "A modification for Donkey Kong 64 that enables switching character at any time, without backtracking."
short_description = "A modification for Donkey Kong 64 that enables switching character at any time, without backtracking."
authors = [ "Isotarge", "Ballaam", "Murdyll", "2dos", "Mittenz", "retroben", "Kaze Emanuar", "SubDrag", "runehero123", "Skill", "TJ Blakely", "GloriousLiar", "Adam Whitmore", "Znernicus", "Zorulda", "ChristianVega64", "Rain", "Shygoo", "tj90241" ]
game_id = "dk64"
minimum_recomp_version = "1.0.0"

[inputs]
elf_path = "build/mod.elf"
mod_filename = "dk64_tag_anywhere"
func_reference_syms_file = "Dk64Syms/dump.toml"
data_reference_syms_files = [ "Dk64Syms/data_dump.toml" ]
additional_files = ["thumb.dds"]