# Fields that end up in the mod's manifest.
[manifest]
# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "dk64_tag_anywhere"
# Version of this mod.
version = "1.0.1"
# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "DK64 Tag Anywhere"
# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  "A modification for Donkey Kong 64 that enables switching character at any time, without backtracking."
# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "A modification for Donkey Kong 64 that enables switching character at any time, without backtracking."
# Authors of this mod.
authors = [ "IsoTarge", "Tom Ballaam", "Murdyll", "2dos", "Mittenz", "retroben", "Kaze Emanuar", "SubDrag", "runehero123", "Skill", "TJ Blakely", "GloriousLiar", "Adam Whitmore", "Znernicus", "Zorulda", "ChristianVega64", "Rain", "Shygoo", "tj90241" ]
# ID of the target recomp game.
game_id = "dk64"
# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.0.0"

# Inputs to the mod tool.
[inputs]
# Input elf file to generate a mod from.
elf_path = "build/mod.elf"
# Output mod filename.
mod_filename = "dk64_tag_anywhere"
# Reference symbol files.
func_reference_syms_file = "Dk64Syms/dump.toml"
data_reference_syms_files = [ "Dk64Syms/data_dump.toml" ]
# Additional files to include in the mod.
additional_files = ["thumb.dds"]