name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get install -y clang lld make

      - name: Build ELF
        run: make

      - name: Download RecompModTool
        run: |
          curl -L -o RecompModTool https://github.com/N64Recomp/N64Recomp/releases/download/mod-tool-release/RecompModTool
          chmod +x RecompModTool

      - name: Package mod
        run: |
          mkdir -p bin
          ./RecompModTool mod.toml bin
          zip -j ./bin/dk64_tag_anywhere.zip ./bin/dk64_tag_anywhere.nrm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dk64_tag_anywhere
          path: bin/dk64_tag_anywhere.zip

      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: bin/dk64_tag_anywhere.zip